// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("e32ad866-751f-4a4e-8d27-17c092218915")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("MediaLibrary.Tests")]
