// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("ddc7f4a4-2ece-45e9-92da-e1cd984b631b")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("MediaLibrary.Tests")]
