// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("014b41bd-d68f-4eef-ab83-2c3f9b1bf7e3")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("MediaLibrary.Web")]
