// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("1f8f6a71-d059-4099-b7a0-e5f53fe60614")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("MediaLibrary.Tests")]
