// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("51f09cd8-a007-47cc-a3cc-f8b04342c6ed")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("MediaLibrary")]
